export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'

export const MODAL_SIGNIN = 'MODAL_SIGNIN'
export const MODAL_REGISTRATION = 'MODAL_REGISTRATION'
export const MODAL_CREATION = 'MODAL_CREATION'
export const MODAL_APPLY = 'MODAL_APPLY'

export const USER_LOGGED = 'USER_LOGGED'
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT'


export const UPDATE_TABLES = 'UPDATE_TABLES'
export const UPDATE_TABLE_EXRAINFO = 'UPDATE_TABLE_EXRAINFO'

export const RESULTS_DEALTYPE_SET = 'RESULTS_SET'
export const RESULTS_PLAYER_SET = 'RESULTS_PLAYER_SET'
export const RESUTLTS_WHISTLERS_SET = 'RESUTLTS_WHISTLERS_SET'
export const RESULTS_CONTRACT_SET = 'RESULTS_CONTRACT_SET'
export const RESULTS_TRICKS_SET = 'RESULTS_TRICKS_SET'

export const RESUTLTS_WHISTLERS_RESET = 'RESUTLTS_WHISTLERS_RESET'